version: "3.7"
services:
  nginx:
    image: nginx:1.15
    restart: always
    container_name: container_nginx
    volumes:
      - /Applications/docker/wordpress/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /Applications/docker/wordpress/nginx/config/wordpress-test.com.conf:/etc/nginx/conf.d/wordpress-test.com.conf
      - /Applications/docker/wordpress/nginx/log:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Bangkok
    external_links:
      - container_apache_php
    networks:
      network_wordpress: 
        ipv4_address: 172.0.0.11

  wordpress:
    image: wordpress
    container_name: container_wordpress
    restart: always
    ports:
      - "81:80"
    environment:
      WORDPRESS_DB_HOST: container_mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Aa123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /Applications/docker/wordpress/apache/config/php.ini:/usr/local/etc/php/php.ini
      - /Applications/docker/wordpress/apache/config/apache2.conf:/etc/apache2/apache2.conf
      - /Applications/docker/wordpress/apache/config/wordpress-test.com.conf:/etc/apache2/sites-enabled/wordpress-test.com.conf
      - /Applications/docker/wordpress/apache/data/wordpress-test:/var/www/html
      - /Applications/docker/wordpress/apache/log:/var/log/apache2
    networks:
      network_wordpress:
        ipv4_address: 172.0.0.12

  mysql:
    image: mysql:5.7
    restart: always
    container_name: container_mysql
    command: --init-file /data/application/init.sql
    volumes:
      - /Applications/docker/wordpress/mysql/config/init.sql:/data/application/init.sql
      - /Applications/docker/wordpress/mysql/config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - /Applications/docker/wordpress/mysql/data:/var/lib/mysql
      - /Applications/docker/wordpress/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=Aa123456
    networks:
      network_wordpress:
        ipv4_address: 172.0.0.13

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    restart: always
    container_name: container_phpmyadmin
    ports:
      - "82:80"
    environment:
      - PMA_HOST=container_mysql
    external_links:
      - container_mysql
    networks:
      network_wordpress:
        ipv4_address: 172.0.0.14

networks:
  network_wordpress:
    name: global_wordpress
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
